export const STATES_LIST = [
    "Maharashtra",
    "Rajasthan",
    "Delhi",
    "Karnataka",
    "Gujarat",
    "Tamil Nadu",
    "Telangana",
    "West Bengal",
    "Bihar",
    "Uttar Pradesh",
    "Madhya Pradesh",
    "Chattisgarh",
    "Odisha",
    "Jammu & Kashmir",
    "Andhra Pradesh",
    "Kerala",
    "Uttarakhand",
    "Punjab",
    "Assam",
    "Jharkhand",
];
